export default {
  users: {
    login: '@@USERS/LOGIN',
    loginFailure: '@@USERS/LOGIN_FAILURE',
    loginSuccess: '@@USERS/LOGIN_SUCCESS',
    add: '@@USERS/ADD',
    added: '@@USERS/ADDED',
    addFail: '@@USERS/ADD_FAIL',
    list: '@@USERS/LIST',
    listSuccess: '@@USERS/LIST_SUCCESS',
    listFail: '@@USERS/LIST_FAIL',
    delete: '@@USERS/DELETE',
    deleted: '@@USERS/DELETED',
    deleteFail: '@@USERS/DELETE_FAIL',
    change: '@@USERS/CHANGE',
    changed: '@@USERS/CHANGED',
    changeFail: '@@USERS/CHANGE_FAIL',
    logout: '@@USERS/LOGOUT',
  },
  groups: {
    add: '@@GROUPS/ADD',
    added: '@@GROUPS/ADDED',
    addFail: '@@GROUPS/ADD_FAIL',
    list: '@@GROUPS/LIST',
    listSuccess: '@@GROUPS/LIST_SUCCESS',
    listFail: '@@GROUPS/LIST_FAIL',
    remove: '@@GROUPS/REMOVE',
    removed: '@@GROUPS/REMOVED',
    removeFail: '@@GROUPS/REMOVE_FAIL',
  },
  tests: {
    add: '@@TEST/ADD',
    added: '@@TEST/ADDED',
    addFail: '@@TEST/ADD_FAIL',
    remove: '@@TEST/REMOVE',
    removed: '@@TEST/REMOVED',
    removeFail: '@@TEST/REMOVE_FAIL',
    getTestSuite: '@@TEST/GET_TEST_SUITE',
    testSuiteGot: '@@TEST/TEST_SUITE_GOT',
    testSuiteGetFail: '@@TEST/TEST_SUITE_GET_FAIL',
    getAllTests: '@@TESTS/GET_ALL',
    gotAllTests: '@@TESTS/GOT_ALL',
    getAllTestsFail: '@@TESTS/GET_ALL_TESTS_FAIL',
    get: '@@TESTS/GET',
    got: '@@TESTS/GOT',
    getFail: '@@TESTS/GET_FAIL',
    edit: '@@TESTS/EDIT',
    edited: '@@TESTS/EDITED',
    editFailed: '@@TESTS/EDIT_FAILED'
  },
  result: {
    getAllResults: '@@RESULTS/GET_ALL_RESULTS',
    gotAllResults: '@@RESULTS/GOT_ALL_RESULTS',
    getAllResultsFail: '@@RESULTS/GET_ALL_RESULTS_FAIL',
    saveResult: '@@RESULTS/SAVE_RESULT',
    savedResult: '@@RESULTS/SAVED_RESULT',
    saveResultFail: '@@RESULTS/SAVE_RESULT_FAIL'
  }
}